version: "3.9"
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      TZ: "Europe/Stockholm"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
